/// <reference path="typings/main.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/extensions/string.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Models/Point.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Models/Parameter.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Services/Helpers/RequestInfo.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Services/HTTPServiceBase.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Services/SearchAPIService.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Events/Delegate.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Events/EventArgs.d.ts" />
/// <reference path="bower_components/wim_angular/dist/typings/Events/EventHandler.d.ts" /> 
//# sourceMappingURL=_references.js.map